apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "nginx.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
